### ISSUE TITLE
Transfer maintenance/ownership of this repository?

### ISSUE THREAD

**Issue by nicoddemus** [pytest-dev/pytest-twisted#11]
As discussed in #10, it has been claimed that @christianmlong is no longer actively maintaining this plugin, and @schmir also does not maintain it anymore.

@vtitor has stepped in and would like to become a maintainer, so I've sent @christianmlong an email asking him if it was OK to make @vtitor the new admin of this repository. We will have to wait at least a month to move this forward though, as stated by [our policy](https://github.com/pytest-dev/pytest/blob/master/CONTRIBUTING.rst#submitting-plugins-to-pytest-dev):

> Repository owners can rest assured that no pytest-dev administrator will ever make releases of your repository or take ownership in any way, except in rare cases where someone becomes unresponsive after months of contact attempts. As stated, the objective is to share maintenance and avoid "plugin-abandon".

**Comment by nicoddemus** [comment]
@christianmlong @schmir do you have release rights to the project on PyPI? If so, could you grant me release rights as well?

**Comment by nicoddemus** [comment]
@christianmlong has replied to my email and said he will no longer maintain the repository and agrees to transfer the control over to @vtitor. 👍

**Comment by nicoddemus** [comment]
@vtitor just sent you an invitation. 👍

**Comment by schmir** [comment]
I still have access to pypi and can grant rights. I would need your pypi usernames to do so.

**Comment by nicoddemus** [comment]
Mine is also `nicoddemus`, thanks!

**Comment by vtitor** [comment]
@nicoddemus, @schmir, @christianmlong Guys, thank you very much! 👍 
Mine is ```vtitor```, thanks!

**Comment by schmir** [comment]
@nicoddemus @vtitor you're now both owner of pytest-twisted on pypi

Thanks for taking over maintainership @vtitor
