### ISSUE TITLE
Missing git tag for 1.13.3 release

### ISSUE THREAD

**Issue by felixonmars** [pytest-dev/pytest-twisted#139]
It would be nice to keep PyPI releases and git tags in sync :)

**Comment by altendky** [comment]
It would...  sorry and thank you.

**Comment by altendky** [comment]
https://github.com/pytest-dev/pytest-twisted/tree/v1.13.3

**Comment by felixonmars** [comment]
Thanks! Updated the [Arch package](https://archlinux.org/packages/community/any/python-pytest-twisted/) accordingly.
