### ISSUE TITLE
Add badges to README.rst

### ISSUE THREAD

**Issue by altendky** [pytest-dev/pytest-twisted#22]
Unless you would specifically prefer not to have them I'll add badges to the `README.rst`.

@vtitor, I would need you to get these for me.  I generally use the SVG badges.
https://www.appveyor.com/docs/status-badges/

Publicly accessible ones are:
Travis: ![](https://travis-ci.org/pytest-dev/pytest-twisted.svg?branch=master)
Python Versions: ![](https://img.shields.io/pypi/pyversions/pytest-twisted.svg)

I'll add the Python versions to the `setup.py` so that the last badge will actually show something useful after the next PyPi release.

**Comment by vtitor** [comment]
@altendky Thanks for this, appveyor: https://ci.appveyor.com/api/projects/status/us5l0l9p7hyp2k6x/branch/master?svg=true

**Comment by vtitor** [comment]
Thanks!
