### ISSUE TITLE
missing license

### ISSUE THREAD

**Issue by arunpersaud** [pytest-dev/pytest-twisted#29]
Would be great to include a license file in git and also in the tar-ball. Setup.py mentions BSD, but there are several version (2-clause, 3-clause, etc). Having the LICENSE in the tar-ball also makes packaging for linux distributions easier (can't currently update the openSUSE package because of this issue).

**Comment by vtitor** [comment]
@arunpersaud Thanks for this, I have added a license file to the new [1.8](https://github.com/pytest-dev/pytest-twisted/releases/tag/1.8) release.
