### ISSUE TITLE
Maintenance handoff

### ISSUE THREAD

**Issue by altendky** [pytest-dev/pytest-twisted#42]
https://github.com/pytest-dev/pytest-twisted/pull/34#issuecomment-436625151
> @altendky Unfortunately, I do not have enough time to maintain the repository. Do you want to take over maintainership?

@vtitor, I'll do what I can.  I guess we'll need to get me full admin rights (or whatever they are called) to this repository and PyPI?  I see that last time @nicoddemus was involved (#11).  If there are other points we can add them below as well.

* [x] PyPI rights for @altendky
* [x] GitHub rights for @altendky
* [x] AppVeyor
* [x] Travis

**Comment by vtitor** [comment]
@altendky I have granted you access to PyPI project

**Comment by altendky** [comment]
I see it listed when I log in to PyPI and I see the settings tab on the GitHub repository page.  Thanks.

I guess there's also AppVeyor and Travis?  How are those handled?  (and while we're discussing it, maybe CircleCI as well)

**Comment by altendky** [comment]
@nicoddemus, it looks like I've got access to settings on Travis for pytest-twisted now but not on AppVeyor.  I do see something about pytestbot but it doesn't seem to get me pytest-twisted settings access.

![image](https://user-images.githubusercontent.com/543719/48314853-a6734b00-e59d-11e8-9569-19538d850304.png)

**Comment by altendky** [comment]
@nicoddemus, not that there's any rush here but would it make sense to shift the AppVeyor build into the pytestbot account/team/whatever now?  The repo and the Travis tests are already owned by 'pytest'.  I'm suspecting there aren't any secrets I need from the existing build.

**Comment by nicoddemus** [comment]
Sorry about the delay here, it seems this message slipped through the cracks.

I've added `pytest-twisted` to the `pytestbot` account. 👍 

@altendky please check that you have access.

**Comment by altendky** [comment]
@nicoddemus it appears I do have permissions at https://travis-ci.org/pytest-dev/pytest-twisted/settings.  Thanks.  Now to see if I'm any good at managing a project...

**Comment by altendky** [comment]
like...  actually checking the right server.  :[

**Comment by altendky** [comment]
@nicoddemus, no, I don't get a `Settings` link at https://ci.appveyor.com/project/pytestbot/pytest-twisted.  I do have `pytestbot` in my list in the upper left corner, along with my account.

![image](https://user-images.githubusercontent.com/543719/50790845-0f213000-128e-11e9-87e9-0603be6c4387.png)

**Comment by nicoddemus** [comment]
Please take another look now. 👍

**Comment by altendky** [comment]
Looks the same.  I tried logging in fresh in an incognito window just in case.

**Comment by nicoddemus** [comment]
Argh I forgot to save. 😅 Please try again.

**Comment by altendky** [comment]
Looks good, thanks.
