### ISSUE TITLE
release new version with pytest 4.1 compatibility

### ISSUE THREAD

**Issue by ktdreyer** [pytest-dev/pytest-twisted#60]
Would you please release a new version based on master? It would be great to run `pip install pytest-twisted` and have a version that works with the latest pytest 4.1.

**Comment by altendky** [comment]
Sorry I haven't gotten it done yet.  I was trying to round up a couple other changes and get a pre-release out last week to get more feedback.  I've spent the weekend on work.  I'll still try to get it done soon.

**Comment by altendky** [comment]
https://pypi.org/project/pytest-twisted/1.9/

Thanks for nagging me.  If you have issues with the release let's open a new ticket.  Cheers.

**Comment by nicoddemus** [comment]
Awesome, thanks @altendky for the great work!

**Comment by ktdreyer** [comment]
Thanks! I have several Twisted-based libraries that use this.
