### ISSUE TITLE
Please make a new release

### ISSUE THREAD

**Issue by wRAR** [pytest-dev/pytest-twisted#68]
We are working on the asyncio support in Scrapy and need the asyncio reactor support in pytest-twisted, so can you please release a version with it included so that we could install it from PyPI during testing?

Thank you.

**Comment by altendky** [comment]
in progress...

**Comment by altendky** [comment]
https://pypi.org/project/pytest-twisted/1.11/

Please let me know if this works for you or not before we close the issue.  Thanks for bumping me to keep this project 'maintained'.

**Comment by wRAR** [comment]
This works, thank you very much!
