### ISSUE TITLE
The reason behind disabling the plugin by default

### ISSUE THREAD

**Issue by keller00** [pytest-dev/pytest-twisted#9]
Please see my description of my previous problem [here](https://github.com/pytest-dev/pytest/issues/2992).

I wanted to ask why do we have to explicitly enable this plugin? Based on what's written [here](https://docs.pytest.org/en/2.7.3/plugins.html?highlight=re#external-plugins):

```If a plugin is installed, pytest automatically finds and integrates it, there is no need to activate it. ```

But having to activate this plugin separately goes against this.

**Comment by vtitor** [comment]
@keller00 Thanks. I guess activate the plugin by default looks like a good idea. And this has been released: https://pypi.org/project/pytest-twisted/1.6/
